export interface Transaction {
  id: string;
  date: string;
  title: string;
  subtitle: string;
  category: string;
  catClass: string;
  amount: string;
  amountClass: string;
  property: string;
  highlight: boolean;
  icon?: string;
}

export const categoryOptions = [
  { label: "Capital Improvement", catClass: "bg-blue-50 text-blue-600" },
  { label: "Insurance", catClass: "bg-slate-100 text-slate-600" },
  { label: "Rental Income", catClass: "bg-emerald-50 text-emerald-600" },
  { label: "Utilities", catClass: "bg-teal-50 text-teal-600" },
  { label: "Office Supplies", catClass: "bg-blue-50 text-blue-600" },
  { label: "Contractor", catClass: "bg-violet-50 text-violet-600" },
  { label: "Maintenance", catClass: "bg-orange-50 text-orange-600" },
  { label: "Needs Review", catClass: "bg-[#FEF3C7] text-[#92400E]" },
] as const;

export const allTransactions: Transaction[] = [
  {
    id: "txn-001",
    date: "Mar 15, 2024",
    title: "Home Depot - Materials",
    subtitle: "Project #402 - Kitchen Reno",
    category: "Capital Improvement",
    catClass: "bg-blue-50 text-blue-600",
    amount: "-$2,450.00",
    amountClass: "text-on-surface",
    property: "Main St. Loft",
    highlight: false,
  },
  {
    id: "txn-002",
    date: "Mar 14, 2024",
    title: "Liberty Mutual - Premium",
    subtitle: "Policy: LP-998231",
    category: "Insurance",
    catClass: "bg-slate-100 text-slate-600",
    amount: "-$845.20",
    amountClass: "text-on-surface",
    property: "Oak Ridge Estate",
    highlight: false,
  },
  {
    id: "txn-003",
    date: "Mar 14, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Unit 4B - Maxwell",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-600",
    amount: "+$3,200.00",
    amountClass: "text-emerald-600",
    property: "Main St. Loft",
    highlight: false,
  },
  {
    id: "txn-004",
    date: "Mar 13, 2024",
    title: "Stripe - Mktplace",
    subtitle: "Merchant ID: STR-0091",
    category: "Needs Review",
    catClass: "bg-[#FEF3C7] text-[#92400E]",
    amount: "-$1,102.55",
    amountClass: "text-on-surface",
    property: "Downtown Plaza",
    highlight: true,
    icon: "psychology",
  },
  {
    id: "txn-005",
    date: "Mar 12, 2024",
    title: "ConEd - Energy",
    subtitle: "Acc: 771-001-22",
    category: "Utilities",
    catClass: "bg-teal-50 text-teal-600",
    amount: "-$118.40",
    amountClass: "text-on-surface",
    property: "Downtown Plaza",
    highlight: false,
  },
  {
    id: "txn-006",
    date: "Mar 11, 2024",
    title: "Amazon Business - Supplies",
    subtitle: "Order #114-2209831",
    category: "Office Supplies",
    catClass: "bg-blue-50 text-blue-600",
    amount: "-$234.99",
    amountClass: "text-on-surface",
    property: "Main St. Loft",
    highlight: false,
  },
  {
    id: "txn-007",
    date: "Mar 10, 2024",
    title: "Square Payment - Contractor",
    subtitle: "Inv: SQ-4410",
    category: "Contractor",
    catClass: "bg-violet-50 text-violet-600",
    amount: "-$567.00",
    amountClass: "text-on-surface",
    property: "Oak Ridge Estate",
    highlight: false,
  },
  {
    id: "txn-008",
    date: "Mar 9, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Unit 1 - Acme Corp",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-600",
    amount: "+$2,200.00",
    amountClass: "text-emerald-600",
    property: "Downtown Plaza",
    highlight: false,
  },
  {
    id: "txn-009",
    date: "Mar 8, 2024",
    title: "Roto-Rooter - Plumbing",
    subtitle: "Service Call #8811",
    category: "Maintenance",
    catClass: "bg-orange-50 text-orange-600",
    amount: "-$680.00",
    amountClass: "text-on-surface",
    property: "Main St. Loft",
    highlight: false,
  },
  {
    id: "txn-010",
    date: "Mar 7, 2024",
    title: "State Farm - Premium",
    subtitle: "Policy: SF-441200",
    category: "Insurance",
    catClass: "bg-slate-100 text-slate-600",
    amount: "-$412.50",
    amountClass: "text-on-surface",
    property: "Downtown Plaza",
    highlight: false,
  },
  {
    id: "txn-011",
    date: "Mar 6, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Unit B - Torres",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-600",
    amount: "+$1,350.00",
    amountClass: "text-emerald-600",
    property: "Main St. Loft",
    highlight: false,
  },
  {
    id: "txn-012",
    date: "Mar 5, 2024",
    title: "Lowe's - Landscaping",
    subtitle: "Receipt #LW-009211",
    category: "Maintenance",
    catClass: "bg-orange-50 text-orange-600",
    amount: "-$289.75",
    amountClass: "text-on-surface",
    property: "Oak Ridge Estate",
    highlight: false,
  },
  {
    id: "txn-013",
    date: "Mar 4, 2024",
    title: "National Grid - Gas",
    subtitle: "Acc: NG-5500-18",
    category: "Utilities",
    catClass: "bg-teal-50 text-teal-600",
    amount: "-$94.20",
    amountClass: "text-on-surface",
    property: "Main St. Loft",
    highlight: false,
  },
  {
    id: "txn-014",
    date: "Mar 3, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Unit E - Kim",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-600",
    amount: "+$1,450.00",
    amountClass: "text-emerald-600",
    property: "Main St. Loft",
    highlight: false,
  },
  {
    id: "txn-015",
    date: "Mar 1, 2024",
    title: "HVAC Masters - Repair",
    subtitle: "Work Order #HV-3322",
    category: "Maintenance",
    catClass: "bg-orange-50 text-orange-600",
    amount: "-$1,200.00",
    amountClass: "text-on-surface",
    property: "Downtown Plaza",
    highlight: false,
  },
];

export function getTransactionById(id: string): Transaction | undefined {
  return allTransactions.find((t) => t.id === id);
}
